// components/StudentCard.vue
<template>
    <div class="profile-card-container">
        <div @click="jump(student)" class="profile-card">
            <!-- 头像区域 -->
            <div class="avatar-section">
                <el-avatar class="avatar" :src="avatar(student)"></el-avatar>
                <span v-if="student.team_students_num !== undefined" :class="['team-flag', teamFlagColor(student.team_students_num)]">
                    <template v-if="student.team_students_num === 0">未组队</template>
                    <template v-else-if="student.team_students_num == 4">满员</template>
                    <template v-else>{{ student.team_students_num }}/4</template>
                </span>
            </div>
            
            <!-- 内容区域 -->
            <div class="content-section">
                <div class="text">
                    <div class="name" v-if="student.province !== null"> 
                        <div class="province">来自{{ student.province }}的</div> 
                        {{ student.name }} 
                        <label v-if="isNT(student.mbti)" class="mbti-label-NT">{{student.mbti}}</label>
                        <label v-if="isNF(student.mbti)" class="mbti-label-NF">{{student.mbti}}</label>
                        <label v-if="isSJ(student.mbti)" class="mbti-label-SJ">{{student.mbti}}</label>
                        <label v-if="isSP(student.mbti)" class="mbti-label-SP">{{student.mbti}}</label>
                    </div>
                    <div class="name" v-else> {{ student.name }} 
                        <label v-if="isNT(student.mbti)" class="mbti-label-NT">{{student.mbti}}</label>
                        <label v-if="isNF(student.mbti)" class="mbti-label-NF">{{student.mbti}}</label>
                        <label v-if="isSJ(student.mbti)" class="mbti-label-SJ">{{student.mbti}}</label>
                        <label v-if="isSP(student.mbti)" class="mbti-label-SP">{{student.mbti}}</label>
                    </div>
                    <span class="score">匹配指数： <strong>{{ student.score | numRounding }}</strong></span>
                    <div>
                        <span v-for="(trait, traitIndex) in getTraits(student.contact)" :key="traitIndex" class="label">{{trait}}</span>
                    </div>
                    <div class="contact">
                        <div><strong>QQ: </strong>{{ student.qq }}</div>
                        <div><strong>Wechat: </strong>{{student.wechat }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import md5 from "md5";

export default {
    name: "StudentCard",
    props: {
        student: {
            type: Object,
            required: true
        }
    },
    methods: {
        avatar(student) {
            if (student.qq && student.qq.length > 0) {
                return "https://q.qlogo.cn/headimg_dl?dst_uin=" + student.qq + "&spec=640";
            } else {
                const base_url = "https://gravatar.loli.net/avatar/";
                const email = new Date().getFullYear() + "rmmp." + student.id + "@chacuo.net";
                const hash = md5(email);
                return base_url + hash + "?d=retro";
            }
        },
        jump(student) {
            this.$router.push("/roommates/" + student.id);
        },
        getTraits(contact) {
            if (contact && contact.length < 15) {
                return contact.split(/[,，;；]/).map(trait => trait.trim());
            } else {
                return null;
            }
        },
        isNT(mbti) {
            return ['INTJ', 'INTP', 'ENTP', 'ENTJ'].includes(mbti);
        },
        isNF(mbti) {
            return ['INFJ', 'INFP', 'ENFP', 'ENFJ'].includes(mbti);
        },
        isSJ(mbti) {
            return ['ISTJ', 'ISFJ', 'ESTJ', 'ESFJ'].includes(mbti);
        },
        isSP(mbti) {
            return ['ISTP', 'ISFP', 'ESTP', 'ESFP'].includes(mbti);
        },
        teamFlagColor(num) {
            if (num === 0) return 'flag-green';
            if (num === 4) return 'flag-red';
            return 'flag-orange';
        }
    },
    filters: {
        numRounding(num) {
            num = parseFloat(num);
            return isNaN(num) ? num : num.toFixed(2);
        }
    }
};
</script>

<style lang="scss" scoped>
@import url('https://fonts.googleapis.com/css2?family=Belanosima&family=Noto+Serif+SC&display=swap');
.profile-card-container {
    padding: 0px 20px;
    margin: 20px 0;
    container-type: inline-size; /* 启用容器查询 */

    .profile-card {
        border: #e6e6e6 solid 2px;
        border-radius: 12px;
        min-height: 170px;
        cursor: pointer;
        position: relative;
        
        /* 默认垂直布局（组件宽度 < 300px） */
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 20px;

        .avatar-section {
            position: relative;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 15px;
        }

        .content-section {
            flex: 1;
            width: 100%;
            display: flex;
            justify-content: center;
        }

        .avatar {
            width: 100px;
            height: 100px;
            display: block;
        }

        .team-flag {
            position: absolute;
            top: -10px;
            right: -10px;
            z-index: 20;
            padding: 2px 12px 2px 12px;
            border-radius: 0 10px 0 12px;
            font-size: 12px;
            font-weight: bold;
            color: #fff;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        }

        .flag-green {
            background: #4caf50;
        }
        .flag-red {
            background: #ff5252;
        }
        .flag-orange {
            background: #ff9800;
        }

        .text {
            line-height: 1.5;
            overflow: hidden;
            text-align: center;
            font-family: 'Belanosima', sans-serif;
            font-family: 'Noto Serif SC', serif;

            .name{
                font-size: 20px;
                font-weight: bold;

                .province{
                    font-size: 10px
                }
            }

            .score{
                font-size: 14px;
                color: #242424;
                font-family: 'Belanosima', sans-serif;
                font-family: 'Noto Serif SC', serif;
            }

            /* Styling the label */
            .mbti-label-NT {
                display: inline-block;
                background-color: #9b5cff;
                color: #ffffff;
                font-size: 12px;
                padding: 3px 3px;
                border-radius: 10px;
                vertical-align: middle;
                font-family: 'Courier New', Courier, monospace;
            }

            .mbti-label-NF{
                display: inline-block;
                background-color: #00642a;
                color: #fff;
                font-size: 12px;
                padding: 3px 3px;
                border-radius: 10px;
                vertical-align: middle;
                font-family: 'Courier New', Courier, monospace;
            }

            .mbti-label-SJ{
                display: inline-block;
                background-color: #007bff;
                color: #fff;
                font-size: 12px;
                padding: 3px 3px;
                border-radius: 10px;
                vertical-align: middle;
                font-family: 'Courier New', Courier, monospace;
            }

            .mbti-label-SP{
                display: inline-block;
                background-color: #a69d83;
                color: #fff;
                font-size: 12px;
                padding: 3px 3px;
                border-radius: 10px;
                vertical-align: middle;
                font-family: 'Courier New', Courier, monospace;
            }

            .contact{
                font-size: 10px;
                color: #999;
            }

            .label{
                display: inline-block;
                background-color: #ffae00d7;
                color: #fff;
                font-size: 8px;
                padding: 2px 4px;
                border-radius: 4px;
                vertical-align: middle;
                font-family: Arial, Helvetica, sans-serif;
                margin: 2px;
            }
        }
    }

    .profile-card:hover {
        box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1)
    }

    .profile-card.no-score .text {
        top: 40px;
    }
}

/* 容器查询：当组件宽度 >= 300px 时，使用水平布局 */
@container (min-width: 300px) {
    .profile-card-container {
        .profile-card {
            /* 水平布局：头像在左，内容在右 */
            flex-direction: row;
            align-items: flex-start;
            padding: 20px;
            gap: 20px;

            .avatar-section {
                flex-shrink: 0;
                margin-bottom: 0;
                margin-right: 20px;
                display: flex;
                align-items: center;
            }

            .content-section {
                flex: 1;
                justify-content: flex-start;
                display: flex;
                align-items: center;
                margin-top: 20px;
                margin-left: -30px;
            }

            .text {
                text-align: left;
                margin: 0;
            }

            .avatar {
                width: 100px !important;
                height: 100px !important;
            }

            .team-flag {
                top: -5px;
                right: -5px;
            }
        }
    }
}

/* 容器查询：当组件宽度 >= 400px 时，进一步优化布局 */
@container (min-width: 400px) {
    .profile-card-container {
        .profile-card {
            .avatar {
                width: 135px;
                height: 135px;
            }

            .text {
                .name {
                    font-size: 18px;
                }

                .score {
                    font-size: 13px;
                }
            }
        }
    }
}

/* 容器查询：当组件宽度 >= 500px 时，使用更大的头像 */
@container (min-width: 500px) {
    .profile-card-container {
        .profile-card {
            .avatar {
                width: 150px;
                height: 150px;
            }

            .text {
                .name {
                    font-size: 20px;
                }

                .score {
                    font-size: 14px;
                }
            }
        }
    }
}

/* 移动端适配 - 使用传统媒体查询作为后备方案 */
@media (max-width: 768px) {
    .profile-card-container {
        padding: 0px 10px;
        margin: 10px 0;
        
        .profile-card {
            min-height: 150px;
            padding: 15px;
            
            .avatar {
                width: 80px;
                height: 80px;
            }
            
            .text {
                .name {
                    font-size: 16px;
                }
                
                .score {
                    font-size: 12px;
                }
                
                .contact {
                    font-size: 9px;
                }
                
                .label {
                    font-size: 7px;
                    padding: 1px 3px;
                }
            }
        }
    }
}

/* 小屏幕适配 */
@media (max-width: 480px) {
    .profile-card-container {
        padding: 0px 5px;
        
        .profile-card {
            min-height: 140px;
            padding: 10px;
            
            .avatar {
                width: 70px;
                height: 70px;
            }
            
            .text {
                .name {
                    font-size: 14px;
                }
                
                .score {
                    font-size: 11px;
                }
                
                .contact {
                    font-size: 8px;
                }
            }
        }
    }
}


</style>

// src/components/StudentCard.tsx
import { Link } from 'react-router-dom'
import { Card, CardContent } from '@/components/ui/card'
import { cn } from '@/lib/utils'

const MBTI_GROUPS: Record<string, string> = {
  NT: 'bg-violet-600 text-white',
  NF: 'bg-green-700 text-white',
  SJ: 'bg-blue-600 text-white',
  SP: 'bg-amber-600 text-white',
}
const NT = ['INTJ', 'INTP', 'ENTP', 'ENTJ']
const NF = ['INFJ', 'INFP', 'ENFP', 'ENFJ']
const SJ = ['ISTJ', 'ISFJ', 'ESTJ', 'ESFJ']
const SP = ['ISTP', 'ISFP', 'ESTP', 'ESFP']

function getMbtiClass(mbti?: string | null): string {
  if (!mbti) return ''
  if (NT.includes(mbti)) return MBTI_GROUPS.NT
  if (NF.includes(mbti)) return MBTI_GROUPS.NF
  if (SJ.includes(mbti)) return MBTI_GROUPS.SJ
  if (SP.includes(mbti)) return MBTI_GROUPS.SP
  return ''
}

function getTraits(contact?: string | null): string[] {
  if (!contact || contact.length < 15) return []
  return contact.split(/[,，;；]/).map((t) => t.trim()).filter(Boolean)
}

function simpleHash(s: string): string {
  let h = 0
  for (let i = 0; i < s.length; i++) {
    h = (h << 5) - h + s.charCodeAt(i)
    h |= 0
  }
  return Math.abs(h).toString(16)
}

function resolveAssetUrl(url?: string | null): string {
  if (!url) return ''
  if (/^https?:\/\//i.test(url)) return url
  const base = import.meta.env.VITE_API_URL ? String(import.meta.env.VITE_API_URL) : ''
  if (url.startsWith('/')) return `${base}${url}`
  return `${base}/${url}`
}

function getAvatarUrl(student: { avatar_url?: string | null; qq?: string | null; id: number }): string {
  const custom = resolveAssetUrl(student.avatar_url)
  if (custom) return custom
  if (student.qq && student.qq.length > 0) {
    return `https://q.qlogo.cn/headimg_dl?dst_uin=${student.qq}&spec=640`
  }
  const email = `${new Date().getFullYear()}rmmp.${student.id}@chacuo.net`
  return `https://gravatar.loli.net/avatar/${simpleHash(email)}?d=retro`
}

function teamFlagColor(num: number, max: number): string {
  if (num === 0) return 'bg-green-500'
  if (num >= max) return 'bg-red-500'
  return 'bg-yellow-500 text-black'
}

function teamFlagText(num: number, max: number): string {
  if (num === 0) return '未组队'
  if (num >= max) return '已满员'
  return '已组队'
}

function numRounding(num: number | null | undefined): string {
  if (num == null) return '—'
  const n = parseFloat(String(num))
  return isNaN(n) ? '—' : n.toFixed(2)
}

export interface StudentCardProps {
  student: {
    id: number
    name: string
    province?: string | null
    mbti?: string | null
    contact?: string | null
    avatar_url?: string | null
    qq?: string | null
    wechat?: string | null
    score?: number | null
    team_students_num?: number
  }
  teamMaxStudentCount: number
}

export function StudentCard({ student, teamMaxStudentCount }: StudentCardProps) {
  const teamNum = student.team_students_num ?? 0
  const traits = getTraits(student.contact)

  return (
    <Link to={`/roommates/${student.id}`} className="block">
      <Card className="min-h-[180px] cursor-pointer border-primary/20 transition-shadow hover:shadow-md hover:border-primary/40">
        <CardContent className="relative flex flex-col gap-3 p-4">
          <div className={cn('absolute left-2 top-2 rounded px-2 py-0.5 text-xs font-medium text-white', teamFlagColor(teamNum, teamMaxStudentCount))}>
            {teamFlagText(teamNum, teamMaxStudentCount)}
          </div>
          <div className="absolute right-2 top-2 rounded border border-sky-200 bg-sky-100 px-2 py-0.5 text-xs font-medium text-sky-700">
            匹配分数 {numRounding(student.score)}
          </div>
          <div className="flex gap-3 pt-6">
            <img
              src={getAvatarUrl(student)}
              alt=""
              className="h-16 w-16 shrink-0 rounded-full object-cover sm:h-20 sm:w-20"
            />
            <div className="min-w-0 flex-1">
              <div className="font-semibold text-foreground truncate">{student.name}</div>
              {student.province && (
                <div className="text-xs text-muted-foreground truncate">来自 {student.province}</div>
              )}
              {student.mbti && (
                <span className={cn('mt-0.5 inline-block rounded px-1.5 py-0.5 text-xs font-medium', getMbtiClass(student.mbti))}>
                  {student.mbti}
                </span>
              )}
            </div>
          </div>
          {traits.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {traits.map((t) => (
                <span key={t} className="rounded bg-orange-100 px-1.5 py-0.5 text-xs text-orange-800 dark:bg-orange-500/20 dark:text-orange-200">
                  {t}
                </span>
              ))}
            </div>
          )}
          <div className="mt-auto flex flex-wrap items-center gap-x-3 gap-y-1 border-t border-border/60 pt-2 text-xs text-muted-foreground">
            <span>QQ {student.qq ?? '—'}</span>
            <span>微信 {student.wechat ?? '—'}</span>
          </div>
        </CardContent>
      </Card>
    </Link>
  )
}
